[package]
name = "jpre"
version = "0.1.0"
authors = ["Octavia Togami <octavia.togami@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.18"
reqwest = { version = "0.10.8", features = ["blocking", "json"] }
zip = "0.5.8"
tar = "0.4.30"
libflate = "1.0.2"
lazy_static = "1.4.0"
log = "0.4.11"
stderrlog = "0.5.0"
regex = "1.3.9"
console = "0.12.0"
tempdir = "0.3.7"
config = "0.10.1"
either = "1.6.1"
serde = { version = "1.0.116", features = ["derive"] }

[profile.dev]
opt-level = 2

[profile.release]
debug = true
