[package]
name = "jpre"
description = "A JDK management tool"
keywords = ["java", "jdk"]
categories = ["command-line-utilities", "development-tools::build-utils"]
version = "0.1.0"
authors = ["Octavia Togami <octavia.togami@gmail.com>"]
license = "GPL-3.0-or-later"
license-file = "LICENSE.txt"
readme = "README.md"
repository = "https://github.com/octylFractal/java-preloader-reloadeder"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.18"
reqwest = { version = "0.10.8", features = ["blocking", "json"] }
zip = "0.5.8"
tar = "0.4.30"
libflate = "1.0.2"
lazy_static = "1.4.0"
log = "0.4.11"
stderrlog = "0.5.0"
regex = "1.3.9"
console = "0.12.0"
tempdir = "0.3.7"
config = "0.10.1"
either = "1.6.1"
serde = { version = "1.0.116", features = ["derive"] }

[profile.dev]
opt-level = 2

[profile.release]
lto = true
codegen-units = 1
